### ISSUE TITLE
Set up ReviewNB

### ISSUE THREAD

**Issue by piyanatk** [UKZN-Astronomy/hera_corrcal#3]
I have set up ReviewNB for visual differencing, comparing, and commenting on committed changes made to Jupyter notebook files.

@Mdlalose Can you please check? Please check https://github.com/UKZN-Astronomy/hirax_corrcal/issues/6 for the instructions.

**Comment by Mdlalose** [comment]
I have checked it and followed the instruction given to Zarah. All it well.

**Comment by piyanatk** [comment]
Okay. I will close this issue then.
